import { RouteData } from "@/types/sidebar";
import { HiDatabase, HiDocument } from "react-icons/hi";
import { IoMdHeart } from "react-icons/io";
import {
  MdChildCare,
  MdGroup,
  MdHistory,
  MdHome,
  MdManageAccounts,
  MdPerson2,
  MdReport,
  MdSchool,
  MdStar,
} from "react-icons/md";

export const sidebarData: RouteData[] = [
  {
    route: "/",
    children: [],
    icon: <MdHome />,
    name: "Beranda",
  },
  {
    route: "/data-master",
    children: [
      {
        icon: null,
        children: [],
        name: "Provinsi",
        route: "/data-master/province",
      },
      {
        icon: null,
        children: [],
        name: "Kabupaten / Kota",
        route: "/data-master/districts",
      },
      {
        icon: null,
        children: [],
        name: "Kecamatan",
        route: "/data-master/subdistricts",
      },
      {
        icon: null,
        children: [],
        name: "Kelurahan",
        route: "/data-master/wards",
      },
      {
        icon: null,
        children: [],
        name: "Agama",
        route: "/data-master/religion",
      },
      {
        icon: null,
        children: [],
        name: "Golongan",
        route: "/data-master/group",
      },
      {
        icon: null,
        children: [],
        name: "Bagian",
        route: "/data-master/part",
      },
      {
        icon: null,
        children: [],
        name: "Jenis Kelamin",
        route: "/data-master/gender",
      },
      {
        icon: null,
        children: [],
        name: "Jenis Cuti",
        route: "/data-master/leave-type",
      },
      {
        icon: null,
        children: [],
        name: "Kegiatan Anak",
        route: "/data-master/children-activity",
      },
      {
        icon: null,
        children: [],
        name: "Kelompok Pekerjaan",
        route: "/data-master/work-group",
      },
      {
        icon: null,
        children: [],
        name: "Pekerjaan",
        route: "/data-master/profession",
      },
      {
        icon: null,
        children: [],
        name: "Pendidikan",
        route: "/data-master/education",
      },
      {
        icon: null,
        children: [],
        name: "Status Anak",
        route: "/data-master/child-status",
      },
      {
        icon: null,
        children: [],
        name: "Sumber Gaji",
        route: "/data-master/income-source",
      },
      {
        icon: null,
        children: [],
        name: "Status Orang Tua",
        route: "/data-master/parent-status",
      },
      {
        icon: null,
        children: [],
        name: "Status Pasangan",
        route: "/data-master/partner-status",
      },
      {
        icon: null,
        children: [],
        name: "Status Perkawinan",
        route: "/data-master/marital-status",
      },
      {
        icon: null,
        children: [],
        name: "Tunjangan Anak",
        route: "/data-master/child-support",
      },
      {
        icon: null,
        children: [],
        name: "Unit Kerja",
        route: "/data-master/work-unit",
      },
    ],
    icon: <HiDatabase />,
    name: "Data Master",
  },
  {
    route: "/employee",
    children: [],
    icon: <MdGroup />,
    name: "Pegawai",
  },
  {
    route: "/biodata",
    children: [],
    icon: <MdPerson2 />,
    name: "Biodata",
  },
  {
    route: "/education-history",
    children: [],
    icon: <MdSchool />,
    name: "Riwayat Pendidikan",
  },
  {
    route: "/marital-history",
    children: [],
    icon: <IoMdHeart />,
    name: "Status Pernikahan",
  },
  {
    route: "/child-data",
    children: [],
    icon: <MdChildCare />,
    name: "Data Anak",
  },
  {
    route: "/parent-data",
    children: [],
    icon: <MdStar />,
    name: "Data Orang Tua",
  },
  {
    route: "/leaves",
    children: [],
    icon: <MdHistory />,
    name: "Cuti",
  },
  {
    route: "/employment-letter",
    children: [],
    icon: <HiDocument />,
    name: "SK Kerja",
  },
  {
    route: "/report",
    children: [
      {
        icon: null,
        children: [],
        name: "Laporan Pegawai",
        route: "/report/employee-report",
      },
    ],
    icon: <MdReport />,
    name: "Laporan",
  },
  {
    route: "/account",
    children: [
      {
        icon: null,
        children: [],
        name: "Role",
        route: "/account/role",
      },
      {
        icon: null,
        children: [],
        name: "Akun",
        route: "/account/accounts",
      },
      {
        icon: null,
        children: [],
        name: "Akses",
        route: "/account/access",
      },
    ],
    icon: <MdManageAccounts />,
    name: "Akun",
  },
];

export const sidebarDataAdmin: RouteData[] = [
  {
    route: "/",
    children: [],
    icon: <MdHome />,
    name: "Beranda",
  },
  {
    route: "/data-master",
    children: [
      {
        icon: null,
        children: [],
        name: "Provinsi",
        route: "/data-master/province",
      },
      {
        icon: null,
        children: [],
        name: "Kabupaten / Kota",
        route: "/data-master/districts",
      },
      {
        icon: null,
        children: [],
        name: "Kecamatan",
        route: "/data-master/subdistricts",
      },
      {
        icon: null,
        children: [],
        name: "Kelurahan",
        route: "/data-master/wards",
      },
      {
        icon: null,
        children: [],
        name: "Agama",
        route: "/data-master/religion",
      },
      {
        icon: null,
        children: [],
        name: "Golongan",
        route: "/data-master/group",
      },
      {
        icon: null,
        children: [],
        name: "Bagian",
        route: "/data-master/part",
      },
      {
        icon: null,
        children: [],
        name: "Jenis Kelamin",
        route: "/data-master/gender",
      },
      {
        icon: null,
        children: [],
        name: "Jenis Cuti",
        route: "/data-master/leave-type",
      },
      {
        icon: null,
        children: [],
        name: "Kegiatan Anak",
        route: "/data-master/children-activity",
      },
      {
        icon: null,
        children: [],
        name: "Kelompok Pekerjaan",
        route: "/data-master/work-group",
      },
      {
        icon: null,
        children: [],
        name: "Pekerjaan",
        route: "/data-master/profession",
      },
      {
        icon: null,
        children: [],
        name: "Pendidikan",
        route: "/data-master/education",
      },
      {
        icon: null,
        children: [],
        name: "Status Anak",
        route: "/data-master/child-status",
      },
      {
        icon: null,
        children: [],
        name: "Sumber Gaji",
        route: "/data-master/income-source",
      },
      {
        icon: null,
        children: [],
        name: "Status Orang Tua",
        route: "/data-master/parent-status",
      },
      {
        icon: null,
        children: [],
        name: "Status Pasangan",
        route: "/data-master/partner-status",
      },
      {
        icon: null,
        children: [],
        name: "Status Perkawinan",
        route: "/data-master/marital-status",
      },
      {
        icon: null,
        children: [],
        name: "Tunjangan Anak",
        route: "/data-master/child-support",
      },
      {
        icon: null,
        children: [],
        name: "Unit Kerja",
        route: "/data-master/work-unit",
      },
    ],
    icon: <HiDatabase />,
    name: "Data Master",
  },
  {
    route: "/employee",
    children: [],
    icon: <MdGroup />,
    name: "Pegawai",
  },
  {
    route: "/biodata",
    children: [],
    icon: <MdPerson2 />,
    name: "Biodata",
  },
  {
    route: "/education-history",
    children: [],
    icon: <MdSchool />,
    name: "Riwayat Pendidikan",
  },
  {
    route: "/marital-history",
    children: [],
    icon: <IoMdHeart />,
    name: "Status Pernikahan",
  },
  {
    route: "/child-data",
    children: [],
    icon: <MdChildCare />,
    name: "Data Anak",
  },
  {
    route: "/parent-data",
    children: [],
    icon: <MdStar />,
    name: "Data Orang Tua",
  },
  {
    route: "/leaves",
    children: [],
    icon: <MdHistory />,
    name: "Cuti",
  },
  {
    route: "/employment-letter",
    children: [],
    icon: <HiDocument />,
    name: "SK Kerja",
  },
  {
    route: "/report",
    children: [
      {
        icon: null,
        children: [],
        name: "Laporan Pegawai",
        route: "/report/employee-report",
      },
    ],
    icon: <MdReport />,
    name: "Laporan",
  },
];

export const sidebarDataUser: RouteData[] = [
  {
    route: "/",
    children: [],
    icon: <MdHome />,
    name: "Beranda",
  },
  {
    route: "/employee",
    children: [],
    icon: <MdGroup />,
    name: "Pegawai",
  },
  {
    route: "/biodata",
    children: [],
    icon: <MdPerson2 />,
    name: "Biodata",
  },
  {
    route: "/education-history",
    children: [],
    icon: <MdSchool />,
    name: "Riwayat Pendidikan",
  },
  {
    route: "/marital-history",
    children: [],
    icon: <IoMdHeart />,
    name: "Status Pernikahan",
  },
  {
    route: "/child-data",
    children: [],
    icon: <MdChildCare />,
    name: "Data Anak",
  },
  {
    route: "/parent-data",
    children: [],
    icon: <MdStar />,
    name: "Data Orang Tua",
  },
  {
    route: "/leaves",
    children: [],
    icon: <MdHistory />,
    name: "Cuti",
  },
  {
    route: "/employment-letter",
    children: [],
    icon: <HiDocument />,
    name: "SK Kerja",
  },
];
